version: '3.9'

networks:
   ds2_network:
      driver: bridge

services:
   # Frontend
   app:
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Frontend
         dockerfile: Dockerfile
      ports:
         - '3003:3003'
      env_file:
         - ./DS2_Frontend/.env
      volumes:
         - './DS2_Frontend:/app'
         - '/app/node_modules'
      stdin_open: true
      tty: true
      restart: always
      networks:
         - ds2_network

   # Backend
   api:
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Backend
         dockerfile: Dockerfile
      ports:
         - '8003:8003'
      env_file:
         - ./DS2_Backend/.env
      volumes:
         - /app/node_modules
         - ./DS2_Backend:/app
         - /Users/jonkimmel/Desktop/DS2_Files:/DS2_Files
      restart: always
      networks:
         - ds2_network

   # Server
   server:
      container_name: DS2_Server
      environment:
         - TZ=America/Phoenix
      image: nginx
      depends_on:
         - api
         - app
      build:
         context: ./Nginx
         dockerfile: Dockerfile
      ports:
         - '81:81'
      restart: always
      networks:
         - ds2_network
