version: '3.9'

services:
   # Frontend
   app:
      container_name: DS2_Frontend
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Frontend
         dockerfile: Dockerfile
      env_file:
         - ./DS2_Frontend/.env
      volumes:
         - './DS2_Frontend:/app'
         - '/app/node_modules'
      stdin_open: true
      tty: true
      ports:
         - '3001:3001'
      networks:
         - server_customnetwork
         - customnetwork2
      restart: always

   # Backend
   api:
      container_name: DS2_Backend
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Backend
         dockerfile: Dockerfile
      env_file:
         - ./DS2_Backend/.env
      ports:
         - '8001:8001'
      volumes:
         - /app/node_modules
         - ./DS2_Backend:/app
         - /Users/jonkimmel/Desktop/DS2_Files:/DS2_Files
      networks:
         - server_customnetwork
         - customnetwork2
      restart: always

   # Server
   server:
      container_name: Nginx_Server
      environment:
         - TZ=America/Phoenix
      image: nginx
      depends_on:
         - api
         - app
      build:
         context: ./Nginx
         dockerfile: Dockerfile
      ports:
         - '81:81'
         - '444:444'
      networks:
         - server_customnetwork
         - customnetwork2
      volumes:
         - ./Nginx/Server_ssl/192.168.12.209.crt:/etc/nginx/192.168.12.209.crt
         - ./Nginx/Server_ssl/192.168.12.209.key:/etc/nginx/192.168.12.209.key
      restart: always

   # Prometheus
   prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      environment:
         - TZ=America/Phoenix
      ports:
         - '9090:9090'
      volumes:
         - /Users/jonkimmel/Desktop/Code/DS2/prometheus.yml:/etc/prometheus/prometheus.yml
         - prometheus_data:/prometheus # Named volume for Prometheus
      networks:
         - server_customnetwork
         - customnetwork2
      restart: always

   node-exporter:
      image: prom/node-exporter:latest
      volumes:
         - /proc:/host/proc:ro
         - /sys:/host/sys:ro
         - /:/rootfs:ro
      command:
         - '--path.procfs=/host/proc'
         - '--path.sysfs=/host/sys'
         - '--path.rootfs=/rootfs'
      ports:
         - '9100:9100'
      networks:
         - server_customnetwork
         - customnetwork2
      restart: always

   # Grafana
   grafana:
      image: grafana/grafana:latest
      container_name: grafana
      environment:
         - TZ=America/Phoenix
      ports:
         - '5500:3000'
      volumes:
         - grafana_data:/var/lib/grafana
      networks:
         - server_customnetwork
         - customnetwork2
      restart: always

networks:
   server_customnetwork:
      external: true
   customnetwork2:
      driver: bridge

volumes:
   grafana_data:
   prometheus_data: # Added this named volume for Prometheus
