version: '3.9'

networks:
   ds2_network:
      driver: bridge

services:
   # Frontend
   app:
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Frontend
         dockerfile: Dockerfile
      ports:
         - '3003:3003'
      env_file:
         - ./DS2_Frontend/.env
      volumes:
         - './DS2_Frontend:/app'
         - '/app/node_modules'
      stdin_open: true
      tty: true
      restart: always
      networks:
         - ds2_network

   # Backend
   api:
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Backend
         dockerfile: Dockerfile
      ports:
         - '8003:8003'
      env_file:
         - ./DS2_Backend/.env
      volumes:
         - '/app/node_modules'
         - './DS2_Backend:/app'
         - '/Users/jonkimmel/Desktop/DS2_Files:/DS2_Files'
      restart: always
      networks:
         - ds2_network

   # Server (Nginx)
   server:
      container_name: DS2_Server
      environment:
         - TZ=America/Phoenix
      build:
         context: ./Nginx
         dockerfile: Dockerfile
      ports:
         - '80:80' # This line is updated to map port 80 on the host to port 80 in the container
         - '81:81' # Optionally keep this if you want direct access to port 81 as well
      volumes:
         - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf # Ensure this path matches your setup
      restart: always
      networks:
         - ds2_network
