version: '3.9'

networks:
   ds2_network:
      driver: bridge

services:
   app:
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Frontend
         dockerfile: Dockerfile
      ports:
         - '3003:3003'
      env_file:
         - ./DS2_Frontend/.env
      volumes:
         - './DS2_Frontend:/app'
         - '/app/node_modules'
      stdin_open: true
      tty: true
      restart: always
      networks:
         - ds2_network

   api:
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Backend
         dockerfile: Dockerfile
      ports:
         - '8003:8003'
      env_file:
         - ./DS2_Backend/.env
      volumes:
         - '/app/node_modules'
         - './DS2_Backend:/app'
         - '/Users/jonkimmel/Desktop/DS2_Files:/DS2_Files'
      restart: always
      networks:
         - ds2_network

   server:
      container_name: DS2_Server
      environment:
         - TZ=America/Phoenix
      build:
         context: ./Nginx
         dockerfile: Dockerfile
      ports:
         - '443:443' # Only expose port 443 for HTTPS, remove port 80 mapping
      volumes:
         - './Nginx/default.conf:/etc/nginx/conf.d/default.conf'
         - './Nginx/Server_ssl:/etc/nginx/ssl' # Map the SSL directory to the container
      restart: always
      networks:
         - ds2_network
