version: '3.9'

networks:
   ds2_network:
      driver: bridge

services:
   # Frontend
   app:
      container_name: DS2_Frontend
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Frontend
         dockerfile: Dockerfile
      ports:
         - '3001:3001'
      env_file:
         - ./DS2_Frontend/.env
      volumes:
         - './DS2_Frontend:/app'
         - '/app/node_modules'
      stdin_open: true
      tty: true
      restart: always
      networks:
         - ds2_network

   # Backend
   api:
      container_name: DS2_Backend
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Backend
         dockerfile: Dockerfile
      ports:
         - '8001:8001'
      env_file:
         - ./DS2_Backend/.env
      volumes:
         - /app/node_modules
         - ./DS2_Backend:/app
         - /Users/jonkimmel/Desktop/DS2_Files:/DS2_Files
         - ./Nginx/Server_ssl/192.168.12.209.crt:/app/ssl/192.168.12.209.crt
         - ./Nginx/Server_ssl/192.168.12.209.key:/app/ssl/192.168.12.209.key
      restart: always
      networks:
         - ds2_network

   # Server
   server:
      container_name: DS2_Server
      environment:
         - TZ=America/Phoenix
      image: nginx
      depends_on:
         - api
         - app
      build:
         context: ./Nginx
         dockerfile: Dockerfile
      ports:
         - '81:81'
      volumes:
         - ./Nginx/Server_ssl/192.168.12.209.crt:/etc/nginx/192.168.12.209.crt
         - ./Nginx/Server_ssl/192.168.12.209.key:/etc/nginx/192.168.12.209.key
      restart: always
      networks:
         - ds2_network
