version: '3.9'

networks:
   ds2_network:
      driver: bridge
      name: ds2_network

services:
   app:
      container_name: DS2-App
      image: marine1232/ds2-frontend:latest
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Frontend
         dockerfile: Dockerfile
      env_file:
         - ./DS2_Frontend/.env
      volumes:
         - './DS2_Frontend:/app'
         - '/app/node_modules'
      stdin_open: true
      tty: true
      restart: always
      networks:
         - ds2_network

   api:
      container_name: DS2-Api
      image: marine1232/ds2-backend:latest
      environment:
         - TZ=America/Phoenix
      build:
         context: ./DS2_Backend
         dockerfile: Dockerfile
      env_file:
         - ./DS2_Backend/.env
      volumes:
         - '/app/node_modules'
         - './DS2_Backend:/app'
         - '/Users/jonkimmel/Desktop/DS2_Files:/DS2_Files'
      restart: always
      networks:
         - ds2_network

   server:
      container_name: DS2-Server
      image: marine1232/ds2-nginx:latest
      environment:
         - TZ=America/Phoenix
      build:
         context: ./Nginx
         dockerfile: Dockerfile
      ports:
         - '443:443'
      volumes:
         - './Nginx/default.conf:/etc/nginx/conf.d/default.conf'
         - '/Users/jonkimmel/Desktop/Code/DS2/DS2/Nginx/Server_ssl:/etc/nginx/ssl'
      restart: always
      networks:
         - ds2_network
