CREATE TABLE "customer" (
	"customerID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     "customerInformationID" INTEGER NOT NULL,
	"accountID" INTEGER NOT NULL,
     "userID" INTEGER NOT NULL,
	"dateCreated" DATE NOT NULL,
	"isCustomerActive" BOOLEAN NOT NULL,
	"isCustomerBillable" BOOLEAN NOT NULL,
	"isCustomerRecurring" BOOLEAN NOT NULL,
     "billingCycle" VARCHAR NULL,
     "cycleDay" INTEGER NULL
);

CREATE TABLE "customerInformation" (
	"customerInformationID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"accountID" INTEGER NOT NULL,
     "customerID" INTEGER NOT NULL,
     "userID" INTEGER NOT NULL,
	"dateCreated" DATE NOT NULL,
	"customerName" VARCHAR NOT NULL,
	"customerFirstName" VARCHAR NOT NULL,
	"customerLastName" VARCHAR NOT NULL,
	"customerStreet" VARCHAR NULL,
	"customerCity" VARCHAR NULL,
	"customerState" VARCHAR NULL,
	"customerZip" INTEGER NULL,
	"customerPhone" VARCHAR NULL,
	"customerEmail" VARCHAR NULL,
	"isCustomerAddressActive" BOOLEAN NOT NULL,
	"isCustomerPhysicalAddress" BOOLEAN NOT NULL,
	"isCustomerBillingAddress" BOOLEAN NOT NULL,
	"isCustomerMailingAddress" BOOLEAN NOT NULL
);

CREATE TABLE "customerRetainerLedger" (
	"retainerLedgerID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"customerID" INTEGER NOT NULL,
	"accountID" INTEGER NOT NULL,
     "userID" INTEGER NOT NULL,
	"originalAmount" INTEGER NOT NULL,
	"availableAmount" INTEGER NOT NULL,
	"dateCreated" DATE NOT NULL
);

CREATE TABLE "customerInvoices" (
	"customerInvoicesID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     "invoiceNumber" INTEGER NOT NULL,
	"customerInvoiceDetailID" INTEGER NOT NULL,
	"accountID" INTEGER NOT NULL,
	"beginningBalanceInvoiced" INTEGER NOT NULL,
	"totalPaymentsInvoiced" INTEGER NOT NULL,
	"newChargesInvoiced" INTEGER NOT NULL,
	"endingBalanceInvoiced" INTEGER NOT NULL,
	"unpaidBalanceInvoiced" INTEGER NOT NULL,
	"currentBalanceDue" INTEGER NOT NULL,
     "qouteTotal" INTEGER NULL
);

CREATE TABLE "customerInvoiceDetail" (
	"customerInvoiceDetailID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"customerID" INTEGER NOT NULL,
	"customerInformationID" INTEGER NOT NULL,
	"accountID" INTEGER NOT NULL,
     "userID" INTEGER NOT NULL,
	"dateCreated" DATE NOT NULL,
	"paymentDueDate" DATE NOT NULL,
     "isQoute" BOOLEAN NOT NULL
);

CREATE TABLE "customerRetainerSnapshots" (
	"customerRetainerSnapshotID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"customerID" INTEGER NOT NULL,
	"accountID" INTEGER NOT NULL,
     "retainerLedgerID" INTEGER NOT NULL,
	"customerInvoicesID" INTEGER NOT NULL,
     "availableAmountSnapshot" INTEGER NOT NULL
);

CREATE TABLE "outstandingInvoiceSnapshots" (
	"outstandingInvoiceSnapshotID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"customerID" INTEGER NOT NULL,
	"accountID" INTEGER NOT NULL,
     "customerInvoicesID" INTEGER NOT NULL,
	"currentBalanceDueSnapshot" INTEGER NOT NULL
);

CREATE TABLE "customerJobs" (
	"customerJobID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     "qouteID" INTEGER NULL,
	"accountID" INTEGER NOT NULL,
	"customerID" INTEGER NOT NULL,
     "jobDescription" VARCHAR NOT NULL,
     "userID" INTEGER NOT NULL,
	"dateCreated" DATE NOT NULL,
	"isJobComplete" BOOLEAN NULL,
     "jobQouteAmount" BOOLEAN NULL,
     "isQoute" BOOLEAN NOT NULL,
	"jobDiscountPercentage" INTEGER NULL
);

CREATE TABLE "customerJobDescriptions" (
	"jobDescriptionID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"accountID" INTEGER NOT NULL,
	"jobDescription" VARCHAR NOT NULL,
     "bookRate" INTEGER NULL,
     "estimatedStraightTime" INTEGER NULL
);

CREATE TABLE "customerTransactions" (
	"customerTransactionID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"accountID" INTEGER NOT NULL,
	"customerID" INTEGER NOT NULL,
	"customerJobID" INTEGER NOT NULL,
	"userID" INTEGER NOT NULL,
     "customerInvoicesID" INTEGER NOT NULL,
     "dateCreated" DATE NOT NULL,
     "transactionDate" DATE NOT NULL,
	"transactionType" VARCHAR NOT NULL,
	"quantity" INTEGER NOT NULL,
	"unitCost" INTEGER NOT NULL,
	"totalTransaction" INTEGER NOT NULL,
	"isTransactionBillable" BOOLEAN NULL
);

CREATE TABLE "account" (
	"accountID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"accountInformationID" INTEGER NOT NULL,
	"isAccountActive" BOOLEAN NULL
);

CREATE TABLE "accountInformation" (
	"accountInformationID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"accountID" INTEGER NOT NULL,
	"accountName" VARCHAR NOT NULL,
	"accountStreet" VARCHAR NOT NULL,
	"accountCity" VARCHAR NOT NULL,
	"accountState" VARCHAR NOT NULL,
	"accountZip" INTEGER NOT NULL,
	"accountPhone" VARCHAR NOT NULL,
	"accountEmail" VARCHAR NOT NULL,
	"isAccountPhysicalAddress" BOOLEAN NOT NULL,
	"isAccountBillingAddress" BOOLEAN NOT NULL,
	"isAccountMailingAddress" BOOLEAN NOT NULL,
     "isAccountRemitPaymentAddress" BOOLEAN NOT NULL,
     "isAccountInformationActive" BOOLEAN NOT NULL
);

CREATE TABLE "userLogin" (
	"userLoginID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"userLoginName" VARCHAR NULL,
	"userLoginPassword" VARCHAR NULL,
	"isLoginActive" BOOLEAN NULL
);

CREATE TABLE "users" (
	"userID" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"accountID" INTEGER NOT NULL,
     "userLoginID" INTEGER NOT NULL,
	"userFirstName" VARCHAR NULL,
	"userLastName" VARCHAR NULL,
	"displayName" VARCHAR NOT NULL,
	"rate" INTEGER NOT NULL,
	"role" VARCHAR NOT NULL,
	"accessLevel" VARCHAR NOT NULL,
	"isUserActive" BOOLEAN NULL
);
